force-app/main/default/objects/TriggerService__mdt/TriggerService__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Service</label>
    <pluralLabel>Trigger Services</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerService__mdt/fields/ExecutionOrder__c.field-meta.xml
<CustomField>
    <fullName>ExecutionOrder__c</fullName>
    <label>Execution Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TriggerService__mdt/fields/TriggerEvent__c.field-meta.xml
<CustomField>
    <fullName>TriggerEvent__c</fullName>
    <label>Trigger Event</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TriggerService__mdt/fields/TriggerHandler__c.field-meta.xml
<CustomField>
    <fullName>TriggerHandler__c</fullName>
    <label>Trigger Handler</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/pattern-classes/TriggerServiceRepository.cls
public virtual class TriggerServiceRepository extends AbstractRepository{

    public TriggerServiceRepository() {}

    public virtual List<TriggerService__mdt> getTriggerServicesByHandlerAndEvent(String triggerHandler, String triggerEvent) {
        return [
            SELECT 
                ServiceClass__c
                , ExecutionOrder__c 
            FROM 
                TriggerService__mdt 
            WHERE 
                TriggerHandler__c =: triggerHandler AND TriggerEvent__c =: triggerEvent AND IsActive__c = true 
            ORDER BY 
                ExecutionOrder__c
        ];
    }
}